# Generated by Django 4.1.1 on 2022-09-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_inbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'ordering': ('-date_created',)},
        ),
    ]
