# Generated by Django 4.1.1 on 2022-09-23 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallet_wallet_number_alter_wallet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='outstanding_debts',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(500.0)]),
        ),
    ]
