# Generated by Django 4.1.1 on 2022-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_wallet_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_number',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
