# Generated by Django 4.1.1 on 2022-09-23 19:35

import accounts.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_managers_inbox_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('inactive_objects', accounts.models.UserInActiveManager()),
            ],
        ),
    ]
