# Generated by Django 4.1.1 on 2022-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='media/avatar.svg', upload_to='member_profile_picture'),
        ),
    ]
