# Generated by Django 4.1.1 on 2022-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', upload_to='member_profile_picture'),
        ),
    ]
