# Generated by Django 4.1.1 on 2022-09-24 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
