# Generated by Django 4.1.1 on 2022-09-25 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_wallettransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='outstanding_debts',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(500.0)]),
        ),
    ]
