# Generated by Django 4.1.1 on 2022-09-26 05:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('authors', models.TextField(help_text="End Every Name with a \\, e.g, Adekunle, Ciroma Chukwuma/ , the main author's name should be the first")),
                ('thumbnail', models.ImageField(blank=True, default='book_default.png', upload_to='book_thumbnail')),
                ('isbn', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn13', models.CharField(max_length=13)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ratings_count', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('language_code', models.CharField(max_length=7, null=True)),
                ('num_of_pages', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('publisher', models.CharField(blank=True, default='No Publisher', max_length=500, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('-bookID',),
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('date_to_be_returned', models.DateField(null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('debt_incurred_default', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('is_picked', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.book')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_days', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('new_date_of_return', models.DateField(null=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('borrowed_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.borrowedbook')),
            ],
        ),
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('borrowed_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.borrowedbook')),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_system.book')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_requested',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='management_system.genre'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'isbn', 'isbn13')},
        ),
    ]
