# Generated by Django 4.1.1 on 2022-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_alter_borrowedbook_debt_incurred_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='debt_incurred_default',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
