# Generated by Django 4.1.1 on 2022-09-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0004_remove_borrowedbook_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ('-date_requested',)},
        ),
    ]
