# Generated by Django 4.1.1 on 2022-09-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0005_alter_bookrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
    ]
