# Generated by Django 4.1.1 on 2022-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_borrowedbook_is_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
