# Generated by Django 4.1.1 on 2022-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0009_remove_renewalrequest_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreturn',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
