# Generated by Django 4.1.1 on 2022-09-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0011_alter_book_options_alter_book_num_of_pages_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'isbn', 'isbn13')},
        ),
    ]
