# Generated by Django 4.1.1 on 2022-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0012_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='No Publisher', max_length=500, null=True),
        ),
    ]
