# Generated by Django 4.1.1 on 2022-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0013_alter_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='debt_incurred_default',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
