# Generated by Django 4.1.1 on 2022-09-25 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0015_alter_renewalrequest_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequest',
            name='renewal_days',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
