# Generated by Django 4.1.1 on 2022-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0016_renewalrequest_renewal_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalrequest',
            name='renewal_date',
        ),
        migrations.AddField(
            model_name='renewalrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
