# Generated by Django 4.1.1 on 2022-09-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0017_remove_renewalrequest_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalrequest',
            name='new_date_of_return',
            field=models.DateTimeField(null=True),
        ),
    ]
